bamstats:
  title: "Bamstats"
  icon: "dna"
  module: True
  tooltip: "Run Bamstats on BAM file"
  dependencies:
    - target: "jhuaplbio/basestack_orchestrator"
      type: "docker-local"
      build:
        file: "Dockerfile"
        path: "${resourcePath}/server/config/modules/dind/Dockerfile" 
    - source: 
        url: "github.com/theiagen/public_health_viral_genomics/Titan_ONT:fja-quasitools-dev"
        type: "dockstore-configuration"
        remove: false
        target: "${writePath}/workflows/bamstats/Dockstore.json"
      type: "dockstore-configuration" 
      target: "${writePath}/workflows/bamstats/Dockstore.json"
      bind: "${writePath}/workflows/bamstats/:/tmp"
      workingdir: "/tmp"
      command: ["bash", "-c", "dockstore tool convert entry2json --entry quay.io/collaboratory/dockstore-tool-bamstats:1.25-6_1.0 > /tmp/Dockstore.json"]
      overwrite: true
      label: "Bamstats Configuration File"
       
              