version: '2.3'

networks:
  basestack_network:
    name: "basestac-network"
volumes:
    basestack-docker-certs-client:
        name: "basestack-docker-certs-client"
services:
  test_bamstats:
    privileged: false
    init: true
    image: jhuaplbio/basestack_orchestrator
    networks:
      basestack_network:
        aliases:
          - docker
    networks:
      - basestack_network
    volumes: 
        - ${workdir}:/tmp:rw
        - basestack-docker-certs-client:/certs/client:ro
    environment:
        DOCKER_TLS_CERTDIR: "/certs"
    command: "dockstore tool launch --entry quay.io/collaboratory/dockstore-tool-bamstats:1.25-6_1.0 --json /tmp/Dockstore.json"
    restart: "no"
    container_name: bamstats