version: '2.3'

networks:
  basestack_network:

volumes:
  basestack_data:
  basestack_docker:
  basestack_docker_certs_ca:
  basestack_docker_certs_client:

services:
  basestack_orchestrator:
    privileged: true
    image: jhuaplbio/basestack_orchestrator
    stdin_open: true # docker run -i
    networks:
      basestack_network:
        aliases:
          - docker
    tty: true 
    ports:
      - "0.0.0.0:8087:8087"
      - "0.0.0.0:8088:8088"
    build:
      context: .
      dockerfile: Dockerfile
    init: true
    volumes:
      - .:/opt/app
      - basestack_docker:/var/lib/docker
      - basestack_docker_certs_ca:/certs/ca
      - basestack_docker_certs_client:/certs/client
    environment:
      DOCKER_TLS_CERTDIR: "/certs"
    command: "--dns 8.8.8.8"
    restart: unless-stopped
    container_name: basestack_orchestrator  
  basestack_dockstore:
    image: jhuaplbio/basestack_orchestrator
    stdin_open: true # docker run -i
    depends_on:
      - basestack_orchestrator
    tty: true 
    init: true
    volumes:
        - .:/opt/app
        - basestack_docker_certs_client:/certs/client:ro
    environment:
      DOCKER_TLS_CERTDIR: "/certs"
    command: "dockstore tool launch --entry quay.io/collaboratory/dockstore-tool-bamstats:1.25-6_1.0 --json Dockstore.json"
    # command: "bash"
    restart: "no"
    container_name: basestack_dockstore
  basestack_dev_server:
      image: jhuaplbio/basestack_orchestrator
      init: false
      ports:
        - "0.0.0.0:5003:5003"
      networks:
        - default
        - basestack_network
      volumes:
        - .:/opt/app
        - basestack_docker_certs_client:/certs/client:ro
      environment:
        DOCKER_TLS_CERTDIR: "/certs"
      command: "npm run dev:server"
      container_name: basestack_dev_server
  basestack_build_server:
    image: jhuaplbio/basestack_orchestrator
    init: false
    depends_on:
      - basestack_orchestrator
    networks:
      - default
      - basestack_network
    volumes:
      - .:/opt/app
    command: "npm run install_modules"
    container_name: basestack_build_orchestrator
  basestack_bundle:
    image: jhuaplbio/basestack_orchestrator
    init: false
    networks:
      - default
      - basestack_network
    volumes:
      - .:/opt/app
    command: "npm run build"
    container_name: basestack_bundle
