version: '2.3'

networks:
    basestack_network:
services:
    mytax_visualization:
        privileged: false
        image: jhuaplbio/basestack_mytax
        init: true
        networks:
            basestack_network:
                aliases:
                    - docker
        networks:
            - default
            - basestack_network
        command: "bash -c 'cd sunburst && python3 -m http.server 8088'"
        ports:
            - "0.0.0.0:8088:8088"
        restart: "no"
        container_name: mytax_visualization
    mytax_process_db:
        privileged: false
        image: jhuaplbio/basestack_mytax
        networks:
          basestack_network:
            aliases:
                - docker
        volumes:
            - ${inputdir}:/opt/databases/database:rw
        networks:
            - default
            - basestack_network
        command: >
            bash -c "source /opt/conda/etc/profile.d/conda.sh && ls /opt/databases/database && 
            conda activate mytax && ls /opt/databases/database && bash process_krakendb.sh -k /opt/databases/database"
        container_name: mytax_process_db
    mytax_report:
        privileged: false
        image: jhuaplbio/basestack_mytax
        networks:
            basestack_network:
            aliases:
                - docker
        volumes:
            - ${inputdir}:/opt/data:rw
        networks:
            - default
            - basestack_network
        command: >
            bash -c " if [ ${compressed} ]; then tar -xvzf /opt/databases/${db}.tar.gz; fi; 
                source /opt/conda/etc/profile.d/conda.sh && 
                conda activate mytax && 
                kraken --db /opt/databases/${db} --output /opt/data/${input}.out /opt/data/${input} &&
                kraken-report --db /opt/databases/${db}  /opt/data/${input}.out | tee  /opt/data/${input}.report &&
                bash krakenreport_fullstring.sh -i /opt/data/${input}.report -k /opt/databases/${db} -o /opt/data/${input}.fullstring &&
                bash krakenreport2json.sh -i /opt/data/${input}.fullstring -o /opt/data/${input}.json"
        container_name: mytax_report