services:
  - path: "../../data/config/server/services"
    format: "yaml"
  - path: "../../data/config/server/service_dind"
    format: "yaml"
# procedures:
#   - path: "../../data/config/server/procedures"
#     format: "yaml"
#   - path: "../../data/config/server/procedure_dind"
#     format: "yaml"
# modules:
#   - path: "../../data/config/server/modules/dind"
#     format: "yaml"
#     ignores: [
#       "docker-compose.yml"
#     ]
#   - path: "../../data/config/server/modules/workflows"
#     format: "yaml"
#     recursive: true
#     ignores: [
#       "docker-compose.yml"
#     ]
