
target:
  production: "modules"
  development: "stagedModules"
modules:
  - path: "../../data/config/server/config/modules"
    format: "yml"
    recursive: true
    ignores: [
      "docker-compose.yml"
    ]
