version: '2.3'

networks:
  basestack-network:
    name: basestack-network
    driver: bridge
volumes:
  basestack-data:
    name: "basestack-data"
  basestack-docker:
    name: "basestack-docker"
  basestack-docker-certs-ca:
    name: "basestack-docker-certs-ca"
  basestack-docker-certs-client:
    name: "basesack-docker-certs-client"
services:
  basestack_orchestrator:
    privileged: true
    image: jhuaplbio/basestack_orchestrator
    stdin_open: false # docker run -i
    tty: true
    networks:
        basestack-network:
          aliases: 
            - docker
    ports:
      - "0.0.0.0:8087:8087"
      - "0.0.0.0:8088:8088"
    build:
      context: .
      dockerfile: Dockerfile
    init: true
    volumes:
      - .:/opt/app
      - basestack-docker:/var/lib/docker
      - basestack-docker-certs-ca:/certs/ca
      - basestack-docker-certs-client:/certs/client
    environment:
      DOCKER_TLS_CERTDIR: "/certs"
    command: ""
    # command: "--dns 8.8.8.8 && docker container run -it --name test --rm --privileged  jhuaplbio/basestack_mytax bash -c 'apt-get update && apt-get install -y iputils-ping && ping www.google.com'"
    restart: unless-stopped
    container_name: basestack_orchestrator  
  basestack_init:
    image: jhuaplbio/basestack_orchestrator
    stdin_open: true # docker run -i
    depends_on:
      - basestack_orchestrator
    tty: true 
    init: true
    networks:
        - basestack-network
    volumes:
        - .:/opt/app
        - basestack-docker-certs-client:/certs/client:ro
    environment:
      DOCKER_TLS_CERTDIR: "/certs"
    # command: "bash"
    command: "docker run --rm -it --net=host ubuntu apt-get update"
    # command: "docker container run -it --rm 7aa296ad0030 bash -c 'curl https://raw.githubusercontent.com/nextstrain/nextclade/1.2.3/data/sars-cov-2/tree.json'"
    restart: "no"
    container_name: basestack_init
  basestack_dockstore:
    image: jhuaplbio/basestack_orchestrator
    stdin_open: false # docker run -i
    networks:
        - default
        - basestack-network
    depends_on:
      - basestack_orchestrator
    tty: false
    init: true
    volumes:
        - .:/opt/app
        - basestack-docker-certs-client:/certs/client:ro
    environment:
      DOCKER_TLS_CERTDIR: "/certs"
    # command: "dockstore tool launch --entry quay.io/collaboratory/dockstore-tool-bamstats:1.25-6_1.0 --json Dockstore.json"
    command: docker container run -it --name test --rm --privileged  jhuaplbio/basestack_mytax bash -c "apt-get update && apt-get install -y iputils-ping && ping www.google.com"
    # command: "docker container run -it --name test --rm --privileged  jhuaplbio/basestack_mytax bash -c \"apt-get install iputils-ping\" "
    restart: "no"
    container_name: basestack_dockstore
  basestack_dev_server:
      image: jhuaplbio/basestack_orchestrator
      init: false
      ports:
        - "0.0.0.0:5003:5003"
      networks:
        - basestack-network
      volumes:
        - .:/opt/app
        - basestack-docker-certs-client:/certs/client:ro
      environment:
        DOCKER_TLS_CERTDIR: "/certs"
      command: "npm run dev:server"
      container_name: basestack_dev_server
  basestack_build_server:
    image: jhuaplbio/basestack_orchestrator
    init: false
    depends_on:
      - basestack_orchestrator
    networks:
      - default
      - basestack-network
    volumes:
      - .:/opt/app
    command: "npm run install_modules"
    container_name: basestack_build_orchestrator
  basestack_bundle:
    image: jhuaplbio/basestack_orchestrator
    init: false
    networks:
      - default
      - basestack-network
    volumes:
      - .:/opt/app
    command: "npm run build"
    container_name: basestack_bundle
