pavian_default:
  depends: 
    - type: "module"
      id: "pavian"
  image: "florianbw/pavian"
  orchestrated: false #orchestrated means it r
  init: true
  hideStatus: true
  label: "Pavian Default"
  force_restart: true
  ports:  
    - 8087:80
  variables:
    port:
      element: "render"
      from: "80"
      to: "8087"
pavian_orchestrated:
  depends: 
    - type: "module"
      id: "dind"
  # command: ['bash', '-c', 'ls -lht']
  command: ['docker-compose', 'up', '--force-recreate', '--always-recreate-deps', 'pavian']
  init: false
  hideStatus: true
  label: "Pavian Orchestrated"
  force_restart: false
  config: null
  workingdir: /opt/app/pavian
  orchestrated: true #orchestrated means it runs from dind rather than natively on host
  variables:
    composer: 
      element: null
      bind: /opt/app
      bind_parent_dir: true
      source: "${resourcePath}/server/config/modules/workflows/pavian/docker-compose.yml"
    port:
      element: "render"
      from: "80"      
      to: "8097"