- name: "basestack_orchestrator" #Top level is the left-hand selection of the menu and the major module to install 
  workflows: # Workflows are inner tabs. Each inner tab can have multiple images or dependencies associated with it
    - name: "basestack_dind"
      dependencies: 
        - target: "jhuaplbio/basestack_orchestrator"
          type: "docker"
          build:
            command: "pull florianbw/pavian"
      services: # Each workflow can run multiple services or commands
        - command: []
          name: "basestack_dind"
          init: true
          force_restart: false
          config: "dockerConfig.json"
          orchestrated: false

